version: "3.4"
services:
  ropsten.dnp.dappnode.eth:
    image: "ropsten.dnp.dappnode.eth:0.3.3"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.10.1
    volumes:
      - "ropsten:/root/.ethereum/"
    ports:
      - "30303"
      - 30303/udp
      - 30304/udp
    restart: always
    environment:
      - "EXTRA_OPTIONS=--http.api eth,net,web3,txpool"
volumes:
  ropsten: {}
