version: "3.4"
services:
  ropsten.dnp.dappnode.eth:
    image: "ropsten.dnp.dappnode.eth:0.3.5"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.10.20
    volumes:
      - "ropsten:/root/.ethereum/"
    ports:
      - "30303"
      - 30303/udp
      - 30304/udp
    restart: always
    environment:
      - "EXTRA_OPTIONS=--http.api,engine,eth,net,web3,txpool"
      - SYNCMODE
volumes:
  ropsten: {}
